image:
- Visual Studio 2019
- macOS
- Ubuntu

skip_branch_with_pr: true
stack: python 3.11

environment:
  GITHUB_TOKEN:
    secure: KOG9MoWPAWH+GRAHwNL8c3b1NgNIJqJd9Y90XLT7ATX+5Od8DOwEDw1pHrYY1mUZ

install:
- pip install -r requirements.txt

build_script:
- flet pack Flet_App.py --name PySonic --product-name PySonic --icon sound_waves.png --add-data "assets:assets"

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
#   Windows package
# 
for:
-
  matrix:
    only:
    - image: Visual Studio 2019

  after_build:
  - 7z a counter-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: PySonic-windows.zip

#
#   macOS package
# 
-
  matrix:
    only:
    - image: macOS

  after_build:
  - tar -czvf PySonic-macos.tar.gz -C dist PySonic.app

  artifacts:
  - path: PySonic-macos.tar.gz

#
#   Linux package
# 
-
  matrix:
    only:
    - image: Ubuntu

  after_build:
  - tar -czvf PySonic-linux.tar.gz -C dist PySonic

  artifacts:
  - path: PySonic-linux.tar.gz