title = "Temporary Config"

[settings]
FILE = "C:/Users/james/Desktop/Avicii - Levels.webm"
output = "C:/Users/james/Desktop/"
length = 10
size = [1920, 1080]
color = [255, 255, 255]
background = "C:/Users/james/Desktop/background.jpg" # "C:/Users/james/Desktop/waves.mp4" 
frame_rate = 30
width = 6
separation = 4
position = "Bottom"
AISS = false
wave = false
circular_looped_video = false
snowfall = false
zoom = false