title = "Temporary Config"

[settings]
FILE = "C:/Users/james/Desktop/Avicii - Levels.webm"
output = "C:/Users/james/Desktop/"
length = 15
size = [1920, 1080]
color = [255, 255, 255]
background = "C:/Users/james/Desktop/waves.mp4" # "C:/Users/james/Desktop/background.jpg"
frame_rate = 30
width = 6
separation = 4
position = "Center"
AISS = false
wave = true
circular_looped_video = true
snowfall = false
zoom = false