title = "Temporary Config"

[settings]
FILE = "C:/Users/james/Desktop/Random stuff/Soundboard sounds/Free Bird.mp3"
length = 5
size = [1920, 1080]
color = [255, 255, 255]
background = "C:/Users/james/Desktop/pexels-pixabay-417173.jpg"
frame_rate = 30
width = 1
separation = 0
connected_bars = false
horizontal_bars = false
inverted_bars = false
SSAA = false
AISS = false