title = "Temporary Config"

[settings]
FILE = "C:/Users/james/Desktop/All-The-Kids-Are_depressed_remix.wav"
output = "C:/Users/james/Desktop/"
length = 5
size = [1920, 1080]
color = [255, 255, 255]
background = "C:/Users/james/Desktop/waves.mp4"
frame_rate = 30
width = 6
separation = 4
position = "Right"
SSAA = false
AISS = false
solar = false
wave = true
use_gpu = false
memory_compression = false
circular_looped_video = false