title = "Temporary Config"

[settings]
FILE = "C:/Users/james/Desktop/Jeremy Zucker - supercuts (Lyric Video).webm"
output = "C:/Users/james/Desktop/"
length = 215
size = [1920, 1080]
color = [255, 219, 156]
background = "C:/Users/james/Desktop/waves.mp4"
frame_rate = 30
width = 12
separation = 8
position = "Bottom"
SSAA = false
AISS = false
wave = true
use_gpu = false
circular_looped_video = true
snowfall = false
zoom = false