title = "Temporary Config"

[settings]
FILE = "C:/Users/james/Desktop/Jeremy Zucker - supercuts (Lyric Video).webm"
output = "C:/Users/james/Desktop/"
length = 30
size = [1920, 1080]
color = [156, 219, 255]
background = "C:/Users/james/Desktop/pexels-pixabay-417173.jpg"
frame_rate = 30
width = 6
separation = 4
position = "Bottom"
SSAA = false
AISS = false
wave = false
circular_looped_video = false
snowfall = false
zoom = false