title = "Temporary Config"

[settings]
FILE = "C:/Users/james/Desktop/All-The-Kids-Are_depressed_remix.wav"
length = 3
size = [3840, 2160]
color = [255, 255, 255]
background = "C:/Users/james/Desktop/pexels-pixabay-417173.jpg"
frame_rate = 30
width = 6
separation = 4
connected_bars = false
horizontal_bars = false
inverted_bars = false
SSAA = false
AISS = false
solar = false
wave = true