title = "Testing Config 2"

[settings]
FILE = "testing/test_2_audio.wav"
output = "testing/"
length = 5
size = [1920, 1080]
color = [0, 0, 255]
background = [255, 0, 0]
frame_rate = 30
width = 6
separation = 4
position = "Left"
AISS = false
wave = true
circular_looped_video = false
snowfall = false
zoom = false